version: '3.8'  # You can keep this, but check for updates

services:
  crud_api:
    build:
      context: .  # Ensure this is the right context
      dockerfile: Dockerfile  # Ensure this points to your Dockerfile
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Set the environment variable for the application
      - ConnectionStrings__DefaultConnection="server=mysql;port=3306;database=entrevistaTecnicaEncode;user=root;password=isaac123;"  # MySQL connection string
    depends_on:
      - mysql  # Ensure MySQL starts before the API service

  mysql:
    image: mysql:9.0.1  # Specify a version for the MySQL image
    ports:
      - "8445:3306"  # Map host port 8445 to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: isaac123  # Set root password
      MYSQL_DATABASE: entrevistaTecnicaEncode  # Create the database
    volumes:
      - mysql-data:/var/lib/mysql  # Persist data in a volume

volumes:
  mysql-data:  # Define a named volume for MySQL data
