version: '3.8'

services:
  crud_api:
    build:
      context: . 
      dockerfile: Dockerfile  
    ports:
      - "8080:80"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection="server=mysql;port=3306;database=entrevistaTecnicaEncode;user=root;password=isaac123;"
    depends_on:
      - mysql

  mysql:
    image: mysql:9.0.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: isaac123
      MYSQL_DATABASE: entrevistaTecnicaEncode
    volumes:
      - mysql-data:/var/lib/mysql

  migrate:
    build:
      context: . 
      dockerfile: Dockerfile  
    environment:
      - ConnectionStrings__DefaultConnection="server=mysql;port=3306;database=entrevistaTecnicaEncode;user=root;password=isaac123;"
    command: ["dotnet", "ef", "database", "update"]  

volumes:
  mysql-data:
