version: '3.8'

services:
  crud_api:
    build:
      context: .  # Ensure this is the right context
      dockerfile: Dockerfile  # Ensure this points to your Dockerfile
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection="server=mysql;port=3306;database=entrevistaTecnicaEncode;user=root;password=isaac123;"
    depends_on:
      - mysql

  mysql:
    image: mysql:9.0.1
    ports:
      - "8445:3306"
    environment:
      MYSQL_ROOT_PASSWORD: isaac123
      MYSQL_DATABASE: entrevistaTecnicaEncode
    volumes:
      - mysql-data:/var/lib/mysql

  migrate:
    build:
      context: .  # Use the same context as your main service
      dockerfile: Dockerfile  # Use the same Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection="server=mysql;port=3306;database=entrevistaTecnicaEncode;user=root;password=isaac123;"
    command: ["dotnet", "ef", "database", "update"]  # Run the migration command

volumes:
  mysql-data:
